# -*- coding: utf-8 -*-
"""def_calculadora_looping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ws63yQTBsP-DhJRxO8eqAvStbs3TbYdO

#Calculadora com looping
Faça uma função calculadora que os números e as operações serão feitas pelo usuário. O código deve ficar rodando infinitamente até que o usuário escolha a opção de sair. No início, o programa mostrará a seguinte lista de operações:

1: Soma
2: Subtração
3: Multiplicação
4: Divisão
0: Sair

Digite o número para a operação correspondente e caso o usuário introduza qualquer outro, o sistema deve mostrar a mensagem “Essa opção não existe” e voltar ao menu de opções.

Após a seleção, o sistema deve pedir para o usuário inserir o primeiro e segundo valor, um de cada. Depois precisa executar a operação e mostrar o resultado na tela. Quando o usuário escolher a opção “Sair”, o sistema irá parar.

É necessário que o sistema mostre as opções sempre que finalizar uma operação e mostrar o resultado.

##1 - Função calculadora()
No Código abaixo temos a função calculadora. A execução da função está na segunda célula.

obs: a calculadora só será executada na segunda célula!
"""

def calculadora():
 print("Escolha uma entre as opções:")
 print("1: soma")
 print("2: subtração")
 print("3: multiplicação")
 print("4: divisão")
 print("0: sair")
 print()
 operacao = ""
 while operacao != 0:
   print("Escolha a operação que deseja executar:")
   operacao = int(input())
   if(operacao != 0):
     if(operacao < 0 or operacao > 4):
       print("Esta opção não existe!")
       print()
       print("Escolha uma entre as opções:")
       print("1: soma")
       print("2: subtração")
       print("3: multiplicação")
       print("4: divisão")
       print("0: sair")
       print()
     else:
      primeiro_num = ""
      segundo_num = ""
      print("Escolha o primeiro número:")
      primeiro_num = float(input())
      print("Escolha um segundo número:")
      segundo_num = float(input())
   if(operacao == 1):
     if( segundo_num >= 0):
       print(primeiro_num, "+", segundo_num, " = ", primeiro_num + segundo_num)
     else:
       print(primeiro_num, "-", segundo_num/-1, " = ", primeiro_num + segundo_num)
   elif(operacao == 2):
     if( segundo_num >= 0):
      print(primeiro_num, "-", segundo_num, " = ", primeiro_num - segundo_num)
     else:
       print(primeiro_num, segundo_num, " = ", primeiro_num + segundo_num)
   elif(operacao == 3):
     print("(", primeiro_num,")", "*", "(", segundo_num, ")", " = ", primeiro_num * segundo_num)
   elif(operacao == 4):
     if(segundo_num != 0):
       print("(", primeiro_num, ")", "/", "(", segundo_num, ")", " = ", primeiro_num / segundo_num)
     else:
       print("Para divisão, o segundo número precisar ser diferente de 0.")
 print("fim")

"""##2 - Chamando a função calculadora()

Execute essa parte do código
"""

calculadora()